version: '3.8'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Llalalal
      - MYSQL_PASSWORD=ASdmlkasdm
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks: 
      - router
      - nextcloud

  app:
    image: nextcloud:fpm
    links:
      - db
    volumes:
      - nextcloud:/var/www/html:z
    depends_on:
      - db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Omsk
      - NEXTCLOUD_ADMIN_USER=User
      - NEXTCLOUD_ADMIN_PASSWORD=passNEXTCLOUD
      - NEXTCLOUD_TRUSTED_DOMAINS=
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
      - MYSQL_HOST=db
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=ASdmlkasdm
      - MYSQL_DATABASE=nextcloud
    restart: always
    networks: 
      - router
      - nextcloud
  web:
    image: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=router"
      - "traefik.http.routers.nextcloud.rule=Host(`${TRAEFIK_RULE_HOST}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
    ports:
      - 8680:80
    links:
      - app
    volumes:
      - nextcloud:/var/www/html:z
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: always
    networks: 
      - router
      - nextcloud 
networks:
  router:
    external: true
  nextcloud:
volumes:
  nextcloud:
  db:
